### ISSUE TITLE
Filenames that differ only in case

### ISSUE THREAD

**Issue by skissane** [geneb/ScarletDME#5]
`SYSCOM/QMCLIENT.BAS` and `SYSCOM/QMClient.bas` both exist and differ only in case.

Likewise `SYSCOM/QMCLIENT.PB` and `SYSCOM/QMClient.pb`.

This causes issues when checking out this Git repo on machines with case-insensitive filesystems. (Case-insensitive filesystems are the default on both Windows and macOS; although both support case-sensitivity as an option, it is rarely used in practice.)

I am pretty sure this is just a mistake not something done intentionally.

To fix this, delete one of each of the above pairs of files.

(Note that while `QMCLIENT.BAS` and `QMClient.bas` appear to be identical, `QMCLIENT.PB` and `QMClient.pb` appear to differ. I think in the later case the all caps version is the newer one.)

**Comment by geneb** [comment]
Thanks for the info.  I'll add it to the TODO list. :)

g.
