### ISSUE TITLE
Error in Makefile

### ISSUE THREAD

**Issue by dmontaine** [geneb/ScarletDME#57]
Makefile - Lines 268 - 272 throw errors.  The code currently is

        @chown root.root $(SYSTEMDPATH)/scarletdme.service
        @chown root.root $(SYSTEMDPATH)/scarletdmeclient.socket
        @chown root.root $(SYSTEMDPATH)/scarletdmeclient@.service
        @chown root.root $(SYSTEMDPATH)/scarletdmeserver.socket
        @chown root.root $(SYSTEMDPATH)/scarletdmeserver@.service

 Note the periods in root.root.  Replace the periods with colons and the error goes away.

**Comment by WolWise1** [comment]
Fixed in pull request #56
